### ISSUE TITLE
Problem running the editor on Windows10

### ISSUE THREAD

**Issue by jjalexander** [Reken41/Imperialism2_SGEditor#2]
The editor window pops up for a second or two.
It simply goes away.
No error message, nothing.

Can you give more details as to what is required for the editor to work?

**Comment by jjalexander** [comment]
@Reken41 are you still active?

**Comment by Reken41** [comment]
Yes I am :) Oh I see, will try to rebuild it :)

**Comment by jjalexander** [comment]
Are there any requirements like a certain version of .NET framework or anything like that?

**Comment by Reken41** [comment]
> Are there any requirements like a certain version of .NET framework or anything like that?

No there is a bug :) will fix it in a moment :)

**Comment by Reken41** [comment]
Please check now with new release, should be working :)

**Comment by jjalexander** [comment]
Thanks, it works now. Do you intend to release the code also? I would like to make the option for the resource to also be discovered.

**Comment by Reken41** [comment]
> Thanks, it works now. Do you intend to release the code also? I would like to make the option for the resource to also be discovered.

Yes I can do that.

**Comment by jjalexander** [comment]
Thanks.

**Comment by Reken41** [comment]
> Thanks, it works now. Do you intend to release the code also? I would like to make the option for the resource to also be discovered.

Please commit Your changes and new features to this source code :) I've invited You to this project.
